---
title: "R Notebook"
output: html_notebook
---
##MILITARY DATASET

#Loading Libraries
```{r}
library(tidyverse)
```

```{r}
# SNC -> SINGLE NO CHILD; SC <- SINGLE WITH CHILD; JSM <- JOINT SERVICE MARRIAGE; CVM <- CIVILLIAN MARRIAGE; _M <- MALE; _F <- FEMALE; _T <- TOTAL
AirForce_MaritalStatus <- readxl::read_excel("_data/ActiveDuty_MaritalStatus.xls",
                                               sheet = "AirForce",
                                               skip = 9,
                                               col_names = c("d", "Pay Grade", "SNC_M", "SNC_F", "SNC_T", "SC_M", "SC_F", "SC_T", "JSM_M", "JSM_F", "JSM_T", "CVM_M", "CVM_F",                                                                 "CVM_T", "Total_M", "Total_F", "Total_T")
                                               ) %>%
                                               filter(! str_detect(`Pay Grade`,"TOTAL")) %>%
                                               select(! starts_with("d")) %>%
                                               cbind(Branch = "AirForce")

MarineCorps_MaritalStatus <- readxl::read_excel("_data/ActiveDuty_MaritalStatus.xls",
                                               sheet = "MarineCorps",
                                               skip = 9,
                                               col_names = c("d", "Pay Grade", "SNC_M", "SNC_F", "SNC_T", "SC_M", "SC_F", "SC_T", "JSM_M", "JSM_F", "JSM_T", "CVM_M", "CVM_F",                                                                 "CVM_T", "Total_M", "Total_F", "Total_T")
                                               ) %>%
                                               filter(! str_detect(`Pay Grade`,"TOTAL")) %>%
                                               select(! starts_with("d")) %>%
                                               cbind(Branch = "MarineCorps")

Navy_MaritalStatus <- readxl::read_excel("_data/ActiveDuty_MaritalStatus.xls",
                                               sheet = "Navy",
                                               skip = 9,
                                               col_names = c("d", "Pay Grade", "SNC_M", "SNC_F", "SNC_T", "SC_M", "SC_F", "SC_T", "JSM_M", "JSM_F", "JSM_T", "CVM_M", "CVM_F",                                                                 "CVM_T", "Total_M", "Total_F", "Total_T")
                                               ) %>%
                                               filter(! str_detect(`Pay Grade`,"TOTAL")) %>%
                                               select(! starts_with("d")) %>%
                                               cbind(Branch = "Navy")

Army_MaritalStatus <- readxl::read_excel("_data/ActiveDuty_MaritalStatus.xls",
                                               sheet = "Army",
                                               skip = 9,
                                               col_names = c("d", "Pay Grade", "SNC_M", "SNC_F", "SNC_T", "SC_M", "SC_F", "SC_T", "JSM_M", "JSM_F", "JSM_T", "CVM_M", "CVM_F",                                                                 "CVM_T", "Total_M", "Total_F", "Total_T")
                                               ) %>%
                                               filter(! str_detect(`Pay Grade`,"TOTAL")) %>%
                                               select(! starts_with("d")) %>%
                                               cbind(Branch = "Army")
```
```{r}

Combined_MaritalStatus <- dplyr::bind_rows(AirForce_MaritalStatus, MarineCorps_MaritalStatus, Navy_MaritalStatus, Army_MaritalStatus) %>%
  arrange(`Pay Grade`) %>%
  #mutate(SNC_R = SNC_M/SNC_F, SC_R = SC_M/SC_F, JSM_R = JSM_M/JSM_F, CVM_R = CVM_M/CVM_F, Total_R = Total_M/Total_F) %>%
  select(! contains("_T")) #%>%
  #select(! contains("_F"))
Combined_MaritalStatus <- Combined_MaritalStatus[,c("Pay Grade", "Branch", "SNC_M", "SNC_F", "SC_M", "SC_F", "JSM_M", "JSM_F", "CVM_M", "CVM_F", "Total_M", "Total_F")]
#Combined_MaritalStatus
```
```{r}
Combined_MaritalStatus <- Combined_MaritalStatus %>%
  mutate(Grade = str_extract(`Pay Grade`, '[^-]*$'), Type = str_extract(`Pay Grade`, '^[^-]*[^ -]')) %>%
  select(! contains("Pay")) %>%
  select(! contains("Total"))
Combined_MaritalStatus <- Combined_MaritalStatus[, c("Type", "Grade", "Branch", "SNC_M", "SNC_F", "SC_M", "SC_F", "JSM_M", "JSM_F", "CVM_M", "CVM_F")]
#Combined_MaritalStatus
```
```{r}
## pivot (newer functions longer and wider), name_palette
Combined_MaritalStatus <- Combined_MaritalStatus %>%
  pivot_longer(SNC_M:CVM_F, values_to = "Enrolled", names_to = "Status") %>%
  mutate(
    Plan = ifelse(as.character(Status) == "SNC_M" | as.character(Status) == "SNC_F" , "Single", "Family"), 
    Gender = str_extract(as.character(Status), "[^_]*$"),
    Status = ifelse(str_detect(as.character(Status), "S"), "Single", "Married"),
    Enrolled = as.numeric(Enrolled)
    ) %>%
  filter(! Enrolled == 0)
```
```{r}
Combined_MaritalStatus %>%
  mutate(Enrolled = log2(Enrolled)) %>%
  ggplot(aes(x = Gender, y = Enrolled, fill = Gender)) + 
  geom_bar(stat = "identity")+
  facet_wrap(vars(Type)) +
  scale_fill_hue(c = 40) +
  labs(title = "Type vs Gender Enrolled") +
  theme_minimal()
```

```{r}
Combined_MaritalStatus %>%
  mutate(Enrolled = log2(Enrolled)) %>%
  ggplot(aes(x = Gender, y = Enrolled, fill = Gender)) + 
  geom_bar(stat = "identity")+
  facet_wrap(vars(Status)) +
  scale_fill_hue(c = 40) +
  labs(title = "Type vs Marital Status Enrolled") +
  theme_minimal()

Combined_MaritalStatus %>%
  mutate(Enrolled = log2(Enrolled)) %>%
  ggplot(aes(x = Gender, y = Enrolled, fill = Gender)) + 
  geom_bar(stat = "identity")+
  facet_wrap(vars(Plan)) +
  scale_fill_hue(c = 40) +
  labs(title = "Type vs Status Enrolled") +
  theme_minimal()
```

